### ISSUE TITLE
ColorChooserDialog no RGBA property

### ISSUE THREAD

**Issue by harry-cpp** [openmedicus/gtk-sharp#11]
ColorChooserDialog doesn't generate RGBA property, instead it generates GetRGBA and SetRGBA methods, but `GetRGBA(Gdk.RGBA rgba)` doesn't even have a return value.

**Comment by harry-cpp** [comment]
Same goes for ColorChooserWidget

**Comment by mikkeljohnsen** [comment]
I have just made a push that uses GdkRGBA in Gtk. Could you please test if it works ?

I see in this pull request you use "val.Val" and the generated code I have just pushed don't. So please get back to me if it doesn't work.

**Comment by harry-cpp** [comment]
This was not fixed :(

**Comment by harry-cpp** [comment]
Ups, wrong button, silly me...

**Comment by mikkeljohnsen** [comment]
So, it is not working ?

Maybe the cast "Gdk.RGBA ret = (Gdk.RGBA) val;" must be "Gdk.RGBA ret = (Gdk.RGBA) val.Val";

**Comment by harry-cpp** [comment]
> So, it is not working ?

It's still generating GetRGBA and SetRGBA instead of a property and GetRGBA is still not working.

**Comment by mikkeljohnsen** [comment]
Yes, I removed the property, because it did not compile with it. I will see if I can get it to generate the code properly. It generates it correctly with the "use-alpha" property.

**Comment by harry-cpp** [comment]
> Yes, I removed the property, because it did not compile with it. I will see if I can get it to generate the code properly. It generates it correctly with the "use-alpha" property.

You could also stop generating GetRGBA and SetRGBA and manually implement the RGBA property in the class.

**Comment by mikkeljohnsen** [comment]
Could you test the latest push ?

**Comment by harry-cpp** [comment]
Works great, thank you very much for maintaining gtk sharp 3!!!
